name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: ['ubuntu-latest']

    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm install
      - name: Type check
        run: npm run typecheck
      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2